FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git   \
    curl  \
    zip \
    unzip \
    && docker-php-ext-install mysqli \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

WORKDIR /var/www